version: "3"
services:
  wikistorage-app:
    image: wikistorage-app
    ports:
      - "8080:8080"
    networks:
      - wikistorage-network
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql:8
    networks:
      - wikistorage-network
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=wikistorage
      - MYSQL_USER=wiki
      - MYSQL_PASSWORD=wikipass

networks:
  wikistorage-network:
